### ISSUE TITLE
Property 'observable' does not exist on type 'SymbolConstructor'

### ISSUE THREAD

**Issue by PopGoesTheWza** [sindresorhus/is#108]
> Since I found a solution to my problem, this issue is rather informational.

On a small **mono-repo** (`lerna@3.20.2`) project:

- node.js v12.16.1 and npm 6.14.2
- `typescript@^3.8.3` as root `devDependencies`
- `@types/node@^12.12.29` as **root** `devDependencies`
- `@sindre/sorhus@^2.1.0` as **package** `dependencies`

```shell
❯ tsc --build tsconfig.json
node_modules/@sindresorhus/is/dist/index.d.ts:135:13 - error TS2339: Property 'observable' does not exist on type 'SymbolConstructor'.

135     [Symbol.observable](): ObservableLike;
                ~~~~~~~~~~
```

From what I could gather, `observable` on type `SymbolConstructor` is defined in `@types/node@12.12.29` (which is installed in the **root** `node_modules`), but not in `@types/node@13.7.7` (which ends up being installed in the **package's** `node_module` as a side effect.)

One kludgy quick-fix could be to add `@types/node@^12.12.29` in the package's `devDependencies`

Another, arguably cleaner solution is to use `lerna bootstrap --hoist` so that **root** node_modules prevails.

**Comment by Richienb** [comment]
`type-fest` fixed this exact issue in https://github.com/sindresorhus/type-fest/pull/21. Therefore, we just need to fix https://github.com/sindresorhus/is/issues/85.
