### ISSUE TITLE
numericString gives true for string with spaces

### ISSUE THREAD

**Issue by ArfatSalman** [sindresorhus/is#109]
This code  --
```js
is.numericString(' ');
is.numericString('     ');
```
returns true for both cases. 

I was expecting them to return false. Right now, the check is this --
```js
is.string(value) && value.length > 0 && !Number.isNaN(Number(value));
```
`Number` coerces whitespaces to 0 which is not taken into account right now.

I can make a PR if this was not the original intended behavior.

**Comment by sindresorhus** [comment]
Yes, this is a bug. A PR would be lovely :)

**Comment by ArfatSalman** [comment]
On it.

**Comment by gioragutt** [comment]
@ArfatSalman see [`isEmptyOrWhitespace`](https://github.com/sindresorhus/is/blob/master/source/index.ts#L359,L360) which could be used in this check

**Comment by ArfatSalman** [comment]
Yes. Was thinking of the same. Thanks for mentioning. :) @gioragutt

**Comment by gioragutt** [comment]
Also, mentioning the obvious, but just in case - make sure to include test cases for the strings presented in the issue, to make sure the bug will not be reintroduced in future changes 👍🏻
