### ISSUE TITLE
is.function and is.class

### ISSUE THREAD

**Issue by jsneko** [sindresorhus/is#114]
When attempting to use `is.function` and / or `is.class` I am getting a `x is not a function` error. I then noticed that those two methods / functions had underscores (_) appended to their name.

Is that to mean that we should no longer be using them? If not, should the README be changed to reflect their name change?

**Comment by jsneko** [comment]
Plain JavaScript.

**Comment by brandon93s** [comment]
@jsneko please provide the version you're using and a code snippet if this is still an issue.  Source below shows where `is.function` and `is.class` should be available to plain JS:

https://github.com/sindresorhus/is/blob/d528545e02de3396ea900cd93af478292f0697ee/source/index.ts#L629-L650
