### ISSUE TITLE
Not found in npm registry

### ISSUE THREAD

**Issue by KaustubhPatange** [sindresorhus/is#121]
Today while installing this package using npm,
```
> npm install @sindresorhus/is

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sindresorhus%2fis - Not found
npm ERR! 404
npm ERR! 404  '@sindresorhus/is@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: ----
```

It is constantly failing with the above error!

**Comment by VoidZA** [comment]
Also getting this

**Comment by brabberto** [comment]
Same here, was able to install yesterday..

**Comment by talkol** [comment]
also getting this

**Comment by VoidZA** [comment]
Read a few older articles, seems if you use 
`npm login `
and then install the package it works. You can create a user here: https://www.npmjs.com/login?next=/package/npm-cli-login/access

Perhaps logging in simply links the registy? Anyway it did the trick for me.

**Comment by talkol** [comment]
I believe it's an issue with npm

From https://status.npmjs.org/

```
Update - The issue with the npm website was resolved. We are still looking into error telemetry for installation of scoped packages but are seeing signs of improvement.
Aug 6, 09:33 UTC
Identified - We have identified the problematic component and the team is working on a fix.
Aug 6, 09:09 UTC
Update - The ongoing issue may also affect installation of scoped packages. We continue investigating these issues.
Aug 6, 08:55 UTC
Update - We are continuing to investigate this issue.
Aug 6, 08:29 UTC
Investigating - We are investigating reports of issues when accessing the npmjs.com website.
Aug 6, 08:29 UTC
```

**Comment by KaustubhPatange** [comment]
As per @VoidZA `npm login` did the trick for me. Perhaps we should wait for npm to resolve it officially.

**Comment by duongvanba** [comment]
Do anyone know way to fix it ?

**Comment by guptar85** [comment]
Yes after npm login it installed as expected.

**Comment by duongvanba** [comment]
All my server down because I can not update new version :( 
Help me

**Comment by monovasuk** [comment]
Same issue coming for all versions

**Comment by plicas** [comment]
looks like a problem with NPM and not with this package in specific .. https://status.npmjs.org/

**Comment by techteamsagiam** [comment]
same here getting not found in registry

**Comment by ZabavskyAlex** [comment]
the same problem

**Comment by darkfriend** [comment]
the same problem

**Comment by KaustubhPatange** [comment]
The issue is resolved! `npm install @sindresorhus/is` works now! There are still other packages which have such an issue, npm is taking look into it to fix them as well.

Closing this issue
