### ISSUE TITLE
is.iterable returns IterableIterator instead of Iterable

### ISSUE THREAD

**Issue by xamgore** [sindresorhus/is#128]
Let's dive into the source code:

https://github.com/sindresorhus/is/blob/d528545e02de3396ea900cd93af478292f0697ee/source/index.ts#L184

Only `[Symbol.iterator]` property is checked, meaning the value is at least `Iterable<T>`. It may be `IterableIterator<T>` if the presence of one more property, `next`, is ensured.

```ts
interface Iterable<T> {
    [Symbol.iterator](): Iterator<T>;
}

interface IterableIterator<T> extends Iterator<T> {
    [Symbol.iterator](): IterableIterator<T>;
}

interface Iterator<T, TReturn = any, TNext = undefined> {
    next(...args: [] | [TNext]): ...;
    return?(value?: TReturn): ...;
    throw?(e?: any): ...;
}
```

Do you agree with it? Would you mind I make a PR?

**Comment by sindresorhus** [comment]
Sounds good. Shouldn't it check all the methods though, not just `next`?

**Comment by xamgore** [comment]
`return` and `throw` are optional, so that's fine.

**Comment by sindresorhus** [comment]
I would describe it as a bug fix.

**Comment by sindresorhus** [comment]
@xamgore Still interested in doing a pull request? No worries if not. Just bumping in case you forgot :)

**Comment by sdotson** [comment]
Taking a crack at this here: https://github.com/sindresorhus/is/pull/149
