### ISSUE TITLE
Duplicate identifiers problem

### ISSUE THREAD

**Issue by pvinis** [sindresorhus/is#130]
I added this lib in my deps, and yarn.lock only had this lib as a change too.

I run `yarn tsc` right after, and I get a million `Duplicate identifier` issues.

Here's one of them:
```
node_modules/typescript/lib/lib.dom.d.ts:15973:11 - error TS2300: Duplicate identifier 'URL'.

15973 interface URL {
                ~~~

  node_modules/@types/react-native/globals.d.ts:261:15
    261 declare class URL {
                      ~~~
    'URL' was also declared here.
```

**Comment by sindresorhus** [comment]
This is a known TS bug: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34960
