### ISSUE TITLE
ESM conversion plan: what exports?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/is#137]
What will this module export as a ESM? Will it still be a single default object like it is now or will it export `isUndefined` and the like? 

It could potentially use both:

``` js
export function isUndefined(){}
const is = {
  undefined: isUndefined
}
export default is;
```

**Comment by brandon93s** [comment]
I support the sibling approach as you've outlined:  exporting both the individual named exports and a comprehensive default object give consumers flexibility.  This will allow for both of the following:

```js
import * as is from '@sindresorhus/is'
is.isUndefined(undefined)

// also

import { isUndefined } from '@sindreshorus/is'
isUndefined(undefined)

```

**Comment by fregante** [comment]
Neither example uses the `default` export. Did you mean `import is from` in the first line?

**Comment by sindresorhus** [comment]
I was planning on a default export. I don't really see the benefit of named exports. It becomes very boilerplaty having to import every method and it won't really benefit tree-shaking anyway.

I could allow both, but I prefer having only one way to do something, for consistency.

**Comment by fregante** [comment]
> it won't really benefit tree-shaking anyway

Sure it would? `import {isUndefined} from '@sindresorhus/is'` would definitely treeshake everything else

**Comment by sindresorhus** [comment]
Hmm. I haven't really seen tree-shaking work in practice, but I guess it will be a common request.

I usually prefer having only a single way to do something, but it would be nice to preserve backwards-compatibility and have a nicer API for apps that don't need tree-shaking (servers and CLIs).

**Comment by sindresorhus** [comment]
So the assert API would be `import {assertUndefined} from '@sindresorhus/is'`.

**Comment by sindresorhus** [comment]
Alright. Let's do both.

**Comment by bigbigDreamer** [comment]
@sindresorhus I have a plan to use rollup to package the library and output the es and lib modules respectively, so as to solve this issue. Can I hear your opinion? It is about whether to allow the use of third-party tools for packaging.

**Comment by bigbigDreamer** [comment]
Because rollup packaging natively has tree-shaking.

**Comment by bigbigDreamer** [comment]
If allow, I can complete this issue~
