### ISSUE TITLE
Proposal: Upgrade type signature for `is.infinite()`, `is.integer()`, `is.safeInteger()`

### ISSUE THREAD

**Issue by younho9** [sindresorhus/is#147]
`is.infinite()`, `is.integer()` and `is.safeInteger()` could provide more strongly-typed number type using `type-fest`.

See https://github.com/sindresorhus/ts-extras/issues/23

**Comment by younho9** [comment]
Also, There is `is.infinite()`, but there is no `is.finite()`.

**Comment by sindresorhus** [comment]
PR welcome to both suggestions.

**Comment by sindresorhus** [comment]
The types should be copy-pasted from `type-fest` to https://github.com/sindresorhus/is/blob/main/source/types.ts

**Comment by younho9** [comment]
Since the `Integer` type in `type-fest` is using the [template literal type, more than 4.1 versions of the typescript are required](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types). 😅

**Comment by sindresorhus** [comment]
That's fine.

**Comment by sindresorhus** [comment]
We could not find a way to make it work: https://github.com/sindresorhus/is/pull/152
