### ISSUE TITLE
Proposal: `isTuple`

### ISSUE THREAD

**Issue by younho9** [sindresorhus/is#156]
I don't know if this could be added to [`is`](https://github.com/sindresorhus/is), but it could be useful to infer typescript tuple type value.

```ts
declare const value: unknown;

if(isTuple(value, [is.number, is.string])) {
	value //=> [number, string]
}
```

**Comment by sindresorhus** [comment]
> Can this issue be suggested for is?

Yes, I moved the issue.

**Comment by tommy-mitchell** [comment]
How should this work with ES Tuples (#133)? Maybe `is.tsTuple`? `is.TupleLike`? I know the proposal is still a while out from shipping, but it’s worth future-proofing against.

**Comment by gioragutt** [comment]
I feel `is.tupleLike` feels fine, since it caters to the ts-tuple, and leaves `is.tuple` for when the tc39 proposal is closer

@sindresorhus your thoughts?

**Comment by sindresorhus** [comment]
`is.tupleLike` sounds good.

**Comment by Myfeetarefreezing** [comment]
I'll take a shot at this

**Comment by Myfeetarefreezing** [comment]
closed :)

**Comment by tommy-mitchell** [comment]
@sindresorhus friendly bump that this can be closed :)
