### ISSUE TITLE
Property 'function' does not exist on type 'typeof is'.

### ISSUE THREAD

**Issue by lekterable** [sindresorhus/is#157]
Hi,

I'm trying to check if a given value is a function, but I'm getting the following error:

<img width="841" alt="Screenshot 2022-02-01 at 00 25 02" src="https://user-images.githubusercontent.com/23037261/151889681-a3938afa-3ab8-4ea3-8d97-f7c2a32b76a4.png">

Using the `is.function_` does work, but if this is expected I think we should update the README which also uses the `function` instead of `function_`:
https://github.com/sindresorhus/is#functionvalue

Similarly with other types like `null_` or `class_`.

**Comment by sindresorhus** [comment]
It's a TS limitation only. I have documented it better now: https://github.com/sindresorhus/is/commit/04ccf21dba99e9c07c41a38bcf3e4881c06b1bac
