### ISSUE TITLE
Proposal: is.nonEmptyStringAndNotWhitespace(value)

### ISSUE THREAD

**Issue by ivankatliarchuk** [sindresorhus/is#158]
Currently there is `.emptyStringOrWhitespace(value)`, it would be good to enhance library with `nonEmptyStringAndNotWhitespace(value)`. 

> Returns true if is.nonEmptyString(value) or if it's a string that is all whitespace

Now
```js
.filter((el) => is.nonEmptyString(el) && !is.emptyStringOrWhitespace(el))
```
With negated type
```js
.filter(is.nonEmptyStringAndNotWhitespace)
```

**Comment by sindresorhus** [comment]
Your examples do not do the same thing.

> .filter((el) => is.nonEmptyString(el) && !is.emptyStringOrWhitespace(el))

This check prevents whitespace-only strings

> .filter(s.nonEmptyStringOrWhitespace)

This allows whitespace-only strings. If you read the name.

**Comment by sindresorhus** [comment]
I think what you want is `is.nonEmptyStringAndNotWhitespace`. I'm not sure that's worth it as you could just do:

```js
.filter((el) => !is.emptyStringOrWhitespace(el))
```

**Comment by ivankatliarchuk** [comment]
The proposed solution e.g. `.filter((el) => !is.emptyStringOrWhitespace(el))` does not work.
Example test case https://codesandbox.io/s/npm-playground-forked-u1cypj?file=/src/index.js

1.

```js
const is = require("@sindresorhus/is");

const labels = ["labelA", "", null];
const addLabels = ["labelB", "", undefined, , ,];

function transpose() {
  return [...new Set([...labels, ...addLabels])].filter(
    (el) => is.nonEmptyString(el) && !is.emptyStringOrWhitespace(el)
  );
}

console.log(transpose());
```

`["labelA", "", null, "labelB", undefined]`

2.

```js
const is = require('@sindresorhus/is');

const labels = ['labelA', '', null]
const addLabels =['labelB', '', undefined, , ,]

function transpose() {
  return [...new Set([...labels, ...addLabels])]
    .filter((el) => is.nonEmptyString(el) && !is.emptyStringOrWhitespace(el));
}

console.log(transpose())
```

`["labelA", "labelB"]`

**Comment by ivankatliarchuk** [comment]
Some screenshots as well
![solution-one](https://user-images.githubusercontent.com/5395690/155011663-6027b81e-bb9f-406d-ba35-6dc09884b928.png)
![solution-two](https://user-images.githubusercontent.com/5395690/155011673-d5386e0c-ef69-44ee-b900-56067cc20958.png)

**Comment by ivankatliarchuk** [comment]
Absolutely right it should be `nonEmptyStringAndNotWhitespace`. I changed a topic name

**Comment by ivankatliarchuk** [comment]
https://github.com/renovatebot/renovate/blob/9a103cbb51269ebba7bf1230430c2895d7b1046b/lib/util/string.ts#L29-L31

**Comment by sindresorhus** [comment]
You are checking non-empty twice. It could be:

```js
.filter((el) => is.string(el) && !is.emptyStringOrWhitespace(el))
```

**Comment by sindresorhus** [comment]
But yeah, I think `is.nonEmptyStringAndNotWhitespace` could be useful.

**Comment by ivankatliarchuk** [comment]
MR https://github.com/sindresorhus/is/pull/161

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/is/pull/161
