### ISSUE TITLE
Can't access default export properties when `moduleResolution: 'NodeNext'`

### ISSUE THREAD

**Issue by ifiokjr** [sindresorhus/is#166]
## ✨ Description

`typescript@4.7.2` added [ECMAScript](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js) support. 

With the new setting activated, importing from [this module](https://unpkg.com/browse/@sindresorhus/is@4.6.0/dist/index.d.ts) doesn't recognize any of the properties available on the default export `is`.

Currently, `is` exports itself as a merged namespace and function.

```ts
declare function is(value: unknown): TypeName;
declare namespace is {
  export var undefined: (value: unknown) => value is undefined;
}

export default is;
```

This doesn't seem to recognize properties with the new setting active. 

I think that changing to use an interface as the main export should maintain the current behaviour and fix backward compatibility issues.

```ts
declare interface Is {
  (value: unknown): TypeName;
  undefined: (value: unknown) => value is undefined;
}

declare const is: Is;
export default is;
```

I've also opened an issue in the [TypeScript](https://github.com/microsoft/TypeScript/issues/49298) repo.

<br>

### `tsconfig.json`

```json5
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "moduleResolution": "NodeNext", // This is the added option
  }
}
```

### [Example](https://www.typescriptlang.org/play?target=99&moduleResolution=99&ts=4.8.0-dev.20220528&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBMAznAZlCI4HIACjgB2AJlAKaLQAWArogPRJYDcAUC0gHQHUA2PA8lACqxUikKkiACiwUQpGJUIBzLAEp2iDqXAwAnvwBGAK1IBjGFIDeAXzVA)

```ts
import is from '@sindresorhus/is';

is.nullOrUndefined('something');
// => Property 'nullOrUndefined' does not exist on type 'typeof import("file:///node_modules/@sindresorhus/is/dist/index")

is.emptyObject({});
// => Property 'emptyObject' does not exist on type 'typeof import("file:///node_modules/@sindresorhus/is/dist/index")'.
```

<br>

## 📦 Versions

- `typescript` - **4.7.2**
- `@sindresorhus/is` - **4.6.0**

**Comment by ifiokjr** [comment]
It seems like this is a [TypeScript issue](https://github.com/microsoft/TypeScript/issues/49298#issuecomment-1140404932), and the only way to currently fix it is to upgrade this package to support esm (`type: module`). 

I'll keep it open since it might be useful for those who run into the same issue.

**Comment by sindresorhus** [comment]
Can you try https://github.com/sindresorhus/is/releases/tag/v5.0.0?

**Comment by ifiokjr** [comment]
Thanks @sindresorhus 

The types are working in the [playground](https://www.typescriptlang.org/play?target=99&module=199&ts=4.8.0-dev.20220528&ssl=4&ssc=19&pln=1&pc=1&allowSyntheticDefaultImports=true#code/JYWwDg9gTgLgBMAznAZlCI4HIACjgB2AJlAKaLQAWArogPRJYDcAUC0gHQHUA2PA8lACqxUikKkiACiwUQpGJUIBzLAEp2iDqXAwAnvwBGAK1IBjGFIDeAXzVA) now when the module is set to `NodeNext`.
