### ISSUE TITLE
Question: What is the reason Node.js below version 14.16 is not supported?

### ISSUE THREAD

**Issue by sounisi5011** [sindresorhus/is#170]
The `engines.node` field of this package is [specified as `">=14.16"`](https://github.com/sindresorhus/is/blob/v5.1.0/package.json#L16-L18). However, I do not see why 14.16 is the boundary of what is supported.

Since this package [uses `node:` imports](https://github.com/sindresorhus/is/blob/v5.1.0/source/index.ts#L1), the [minimum version that can work is 14.13.1](https://nodejs.org/api/esm.html#node-imports). Also, I have actually tested and this package still works with 14.13.1 or later.

I looked at [the Node.js changelog](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#14.16.0) and could not see any features available from 14.16.0.

Why does this package only support Node.js 14.16 and above?

**Comment by sindresorhus** [comment]
I have set a baseline of 14.16 for all my packages. Having the same target version everywhere just makes it easier to deal with. Why I picked that version: I took the newest version minus two minor versions.

**Comment by sounisi5011** [comment]
Thanks for answering my personal question!
