### ISSUE TITLE
Confused between class_ docs and implementation

### ISSUE THREAD

**Issue by thetutlage** [sindresorhus/is#172]
The README file has the following description next to the `class_` method.

> Returns `true` for instances created by a class.

By reading this I assume that I am supposed to pass an instance of class and not the class constructor to this method (in order for it to return true).

However, when I look at the implementation, it checks for the class constructor and not an instance (aka object)

https://github.com/sindresorhus/is/blob/main/source/index.ts#L164

---

Does docs need an update? Happy to send a PR for that :)

**Comment by sindresorhus** [comment]
That looks like a typo yes. PR welcome :)
