### ISSUE TITLE
Improve type narrowing for `nonEmptyArray`

### ISSUE THREAD

**Issue by eugene-mohc** [sindresorhus/is#174]
Currently using `nonEmptyArray` on an array variable will type is as `OriginalType[] & [unknown, ...unknown[]]`.

For example if you have a `string[]` variable, it will become `string[] & [unknown, ...unknown[]]`.

This causes problems when trying to access an array element by index. For example:

```ts
const strings: string[] = ['foo', 'bar']

const func = (value: string) => value

if (is.nonEmptyArray(strings)) {
  // Error: cannot assign `unknown` to `string`
  func(strings[0])
}
```

Adding an extra guard doesn't seem to help either, as this produces the same result:

```ts
if (is.nonEmptyArray(strings) && is.array(strings, is.string)) {
  // Error: cannot assign `unknown` to `string`
  func(strings[0])
}
```

It would be useful to either be able to provide a generic type such as `nonEmptyArray<string>` to set the variable's type to be `[string, ...string[]]`, have it be inferred automatically, or to be able to provide a second parameter similar to `is.array` like `is.nonEmptyArray(strings, is.string)`.

Minimal example with the error: https://codesandbox.io/s/flamboyant-microservice-kxt5o4?file=/src/index.ts

**Comment by sindresorhus** [comment]
I don't have the time to look into this, but I have at least added a failing test for this: https://github.com/sindresorhus/is/commit/f3693674f691f08d2b01c73de26992a1f9c7f1ff
