### ISSUE TITLE
v0.2.2

### ISSUE THREAD

**Issue by gioragutt** [sindresorhus/is#18]
@sindresorhus what's your semver policy?

on which occasions do we release?

**Comment by sindresorhus** [comment]
The next release would be 0.3.0, since it will have new features. I usually just release once in a while. For example, I would wait to do 0.3.0 until the two open PRs are merged.

**Comment by sindresorhus** [comment]
Btw, I'm in https://gitter.im/sindresorhus/meta if you need to discuss something :)
