### ISSUE TITLE
is.enumCase method is not a type guard

### ISSUE THREAD

**Issue by vtgn** [sindresorhus/is#205]
Hi,

assert.enumCase() is an assert guard but is.enumCase() is not a type guard, contrary to the other methods. Why this choice?
This is very disturbing and annoying because it requires more work to manage the type of the value given in argument after the call of  is.enumcase(). :/

Regards.

**Comment by sindresorhus** [comment]
Just an oversight. Fixed in the latest update.

**Comment by vtgn** [comment]
@sindresorhus My mistake. I searched for an opened or closed issue about it but there was none, and I didn't think to watch the latest code implementation. I will be careful next time.

Thanks.
Regards.
