### ISSUE TITLE
dataView method?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/is#37]
Should we add a `is.dataView` method?

**Comment by sindresorhus** [comment]
Yes, makes sense for completeness, although I've personally never needed it.

**Comment by sindresorhus** [comment]
Actually, we already have `dataView`: https://github.com/sindresorhus/is#dataviewvalue

**Comment by SamVerschueren** [comment]
I think it's in the docs but it's not in the code. https://github.com/sindresorhus/is/blob/master/source/index.ts#L3

I'm ok with dropping it though, mainly need it for completeness in `Ow`.

**Comment by sindresorhus** [comment]
Oh. How did that happen.

**Comment by sindresorhus** [comment]
We should add it.

**Comment by brandon93s** [comment]
It's even tested! (against `arrayBuffer`). https://github.com/sindresorhus/is/blob/master/source/tests/test.ts#L506-L508

**Comment by sindresorhus** [comment]
Wow, and lol. How did none of us notice.

**Comment by ltetzlaff** [comment]
Nice finding 😅 
[Git blame :innocent:](https://github.com/sindresorhus/is/blame/master/source/tests/test.ts#L506)

**Comment by sindresorhus** [comment]
Yes, I know I'm to blame. Was just surprised no one noticed until now.
