### ISSUE TITLE
`is(promise)` returns `Object` on Node.js 4

### ISSUE THREAD

**Issue by kevva** [sindresorhus/is#40]
While `is.promise(promise)` works across all Node.js versions, just doing `is(promise)` doesn't. The difference is that we check if it has a `then` and a `catch` method in the former.

In Node.js 4 `toString.call(promise)` returns `[object Object]` which differs from newer versions where it returns the correct type.

**Comment by sindresorhus** [comment]
I'd rather just drop Node.js 4 support. Been planning to do that regardless, now that it's EOL in a month. There are also lots of TODO's that could be fixed in the code by dropping Node.js 4 support.

**Comment by gioragutt** [comment]
@sindresorhus I'm for it. That'd mean bumping a major version, due to backward compatibility changes, correct?

**Comment by sindresorhus** [comment]
@gioragutt Awesome!

> That'd mean bumping a major version, due to backward compatibility changes, correct?

No, this module is pre1.0, so it will just be another minor version (which is like major version pre1.0), but I'll handle the version bumping.

**Comment by gioragutt** [comment]
@sindresorhus cool. Seeing as the EOL is `2018-04-30`, there's not much point left to supporting Node for much longer. I'll open an issue regarding that.
