### ISSUE TITLE
Package is not available on NPM registry

### ISSUE THREAD

**Issue by alex996** [sindresorhus/is#45]
Please investigate the issue with the package not resolving on [npmjs.org](https://www.npmjs.com/package/@sindresorhus/is).

Example,

```
> yarn add @sindresorhus/is

yarn add v1.0.2
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@sindresorhus%2fis: Not Found".
```
Same with npm,

```
> npm i @sindresorhus/is

npm ERR! code E404
npm ERR! 404 Not Found: @sindresorhus/is@latest
```

```
> node -v
v9.10.1
> npm -v
5.8.0
> yarn -v
1.0.2
```

**Comment by sindresorhus** [comment]
It resolves for me and lots of other people (It's used in many popular modules).

Use the npm issue tracker for npm support issues: https://github.com/npm/npm
