### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by ischyron** [sindresorhus/is#47]
log verobse:
node: 9.2.0
npm: 5.5.1
(used nvm)

`npm info it worked if it ends with ok
npm verb cli [ '/Users/xxxx/.nvm/versions/node/v9.2.0/bin/node',
npm verb cli   '/Users/xxxx/.nvm/versions/node/v9.2.0/bin/npm',
npm verb cli   'install',
npm verb cli   '-dd',
npm verb cli   '@sindresorhus/is' ]
npm info using npm@5.5.1
npm info using node@v9.2.0
npm verb npm-session 50f73340ea9751c4
npm http fetch GET 404 https://registry.npmjs.org/@sindresorhus%2fis 1521ms
npm verb stack Error: 404 Not Found: @sindresorhus/is@latest
npm verb stack     at fetch.then.res (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/Users/xxxx/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:800:20)
npm verb stack     at tryOnImmediate (timers.js:762:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
npm verb cwd /Users/xxxx/workspace/lego-web
npm verb Darwin 17.2.0
npm verb argv "/Users/xxxx/.nvm/versions/node/v9.2.0/bin/node" "/Users/xxxx/.nvm/versions/node/v9.2.0/bin/npm" "install" "-dd" "@sindresorhus/is"
npm verb node v9.2.0
npm verb npm  v5.5.1
npm ERR! code E404
npm ERR! 404 Not Found: @sindresorhus/is@latest
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2018-04-12T07_47_49_725Z-debug.log
`

**Comment by sindresorhus** [comment]
Use the npm issue tracker for npm install related issues: https://github.com/npm/npm/issues ;)
