### ISSUE TITLE
Consider using util.types

### ISSUE THREAD

**Issue by Hoishin** [sindresorhus/is#48]
Node v10.0.0 introduces new API `util.types.is***(value)`.

https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_types

The API doesn't support all the usefulness in this library, but at lease those new API can be used to make some part of the library faster (I guess), simpler, and lighter.

Node v8.x still remains active for another year though.

**Comment by Hoishin** [comment]
Just noticed this library supports browsers now. Would it make it impossible to use the API?

**Comment by sindresorhus** [comment]
It's probably slower. From the site you linked to:

> Unlike instanceof or Object.prototype.toString.call(value), these checks do not inspect properties of the object that are accessible from JavaScript (like their prototype), **and usually have the overhead of calling into C++**.

And it also would work for the browser, so I don't see any upsides to using those.

**Comment by Hoishin** [comment]
fair enough. thanks for the answer
