### ISSUE TITLE
is there any reason for `is.sharedArrayBuffer` special condition?

### ISSUE THREAD

**Issue by gioragutt** [sindresorhus/is#5]
I'm doing a pull request to remove code repetition, and the sharedArrayBuffer method bothers me. 

```typescript
is.sharedArrayBuffer = x => {
	try {
		return getObjectType(x) === 'SharedArrayBuffer';
	} catch (err) {
		return false;
	}
};
```

Part of the pull request is making a method called `isTypeOf` (WIP, may change after review),

which is:

```typescript
const getObjectType = x => toString.call(x).slice(8, -1);
const isTypeOf = type => x => getObjectType(x) === type;
```

and the usage looks like:

```typescript
is.float32Array = isTypeOf('Float32Array');
is.float64Array = isTypeOf('Float64Array');

is.arrayBuffer = isTypeOf('ArrayBuffer');
```

whereas currently there's a `getObjectType(x) === 'some type'` repetition throughout the code.

What's the reason for `sharedArrayBuffer`s special check?

**Comment by sindresorhus** [comment]
> I'm doing a pull request to remove code repetition

Awesome! I didn't think of using a factory method to simplify further.

> What's the reason for sharedArrayBuffers special check?

Good catch. It's just a leftover from prototyping. You can remove the try/catch.

**Comment by gioragutt** [comment]
@sindresorhus uploaded my PR, I'd love a review. Tomorrow i'll work on some docs perheps.
