### ISSUE TITLE
`is.numericString()`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/is#54]
Sometimes I need to check if a string is a valid number. I guess we could just do `!Number.isNaN(Number(string));`

**Comment by brandon93s** [comment]
The global `isNaN` supports this already, so the implementation could be shortened to just `!isNaN(x)`.

**Comment by ArfatSalman** [comment]
The global `isNaN` returns `true` for `isNaN(undefined)`. However, `Number.isNaN(undefined)` is `false` as expected.
