### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by samuelneff** [sindresorhus/is#57]
Does this library support usage in a browser?

It seems that since it imports `util` and outputs es2016 code to NPM the answer is no. I didn't see anything clearly stating Node-only in the readme though.

If the answer is no, would you accept a PR that made it browser-compliant? It doesn't seem like the changes would be significant.

Thanks,

Sam

**Comment by sindresorhus** [comment]
This module works fine in the browser. If you want to support older browsers, it's up to you to transpile it to be compatible with the browsers you want to support.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

**Comment by samuelneff** [comment]
Thanks!

I didn't realize webpack automatically included [`node-libs-browser`](https://www.npmjs.com/package/node-libs-browser) to fill in things like `util` and also appreciate pointing me to [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin).
