### ISSUE TITLE
Detect `new URL()` instance

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/is#58]
`is.url()` might be too confusing though. Maybe `is.urlObject()`? Feedback welcome.

**Comment by brandon93s** [comment]
`is.URLInstance` or `is.urlInstance` may more accurately convey the new WHATWG Standard instance. 

The docs refer to the [Legacy URL API](https://nodejs.org/api/url.html#url_url_hash) as `urlObject`, which would make `is.urlObject` misleading if it's checking against the newer API.

**Comment by sindresorhus** [comment]
`is.urlInstance` sounds good 👌
