### ISSUE TITLE
Use Typescript 3.0 `unknown` type

### ISSUE THREAD

**Issue by ltetzlaff** [sindresorhus/is#62]
With the new `unknown` type on the horizon in TS 3.0 I feel like we could refactor `any`s to use `unknown` and an explicit cast if necessary. I did not tinker with that yet, just immediately came to my mind upon reading.

https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

What do you think?

**Comment by sindresorhus** [comment]
I had the same immediate thought too: https://github.com/sindresorhus/ow/issues/104

**Comment by sindresorhus** [comment]
Looking through the codebase, I don't really see any good place to use `unknown`. We intentionally support `any` in the input argument so users can pass in anything without having to know the type upfront.

@ltetzlaff Do you see anywhere `unknown` could be used?
