### ISSUE TITLE
Any value in `is.numericValue` or similar?

### ISSUE THREAD

**Issue by alexrussell** [sindresorhus/is#63]
At the moment, `is.number` returns `true` if the passed value is `NaN`. I'd quite like a function that returned `true` iff the passed value was a number with a real numeric value (`0`, `-0`, `+0`, etc. still count, `Infinity` I'd take either way (arguably `true` as Infinity is a real numeric value, just not actually countable)).

Not having yet thought about any edge cases, I imagine this would be a simple function:

```js
export const numericValue = (value) => number(value) && ! nan(value)
```

**Comment by brandon93s** [comment]
`is.number` is a primitive check:

```js
typeof NaN
// => "number"
```

For your purposes, I think composing the methods you've proposed above is your best bet. If you're looking specifically for integers, you could also use: `is.integer() || is.infinite()`. This is best handled as a local function in your code:

```js
const numericValue = val => is.number(val) && !is.nan(value);
```

Supporting these compositions on the module's API is tricky, because one we add one we're pressed to add them all. We typically shy away from simple compositions like this.

**Comment by alexrussell** [comment]
Yeah I totally get that we're trying out best to just mirror how JS works (`NaN` is a number, so `is.number(NaN)` should be `true`), so that is fair enough, I just thought that this kind of composition is especially useful for people who are actually looking to ensure what they have is a real actual usable number.

`NaN` is kind of like a numeric equivalent of `null`: most if not all arithmetic operations with `NaN` end up with a `NaN` value, which I totally get why, but also means our "number" gets "devalued" by it, making it sometimes something we'd like to check for and guard against.

But yes, as you say, it's not hard for me to do this check myself, and indeed that's what I'm doing, but the same could, of course, be said for most of the checks in this library (and, hell, many utility libraries!) 🙂

**Comment by alexrussell** [comment]
Also I have just noticed that you do already include some of these utility-like functions:

- [`is.emptyOrWhitespace`](https://github.com/sindresorhus/is/#emptyorwhitespacevalue)
- [`is.even`](https://github.com/sindresorhus/is/#evenvalue)

`is.integer` and `is.even` are especially pertinent, as they're fulfilling a similar purpose of type checking and then doing a further constraint check to ensure it's a given sub-type of the type. Someone could easy compose `is.number(value) && (value % 2 === 0)` but you provide it to make it so they don't have to.

I hear what you're saying about potentially bloating the library if the floodgates are opened up to every person's individual utility need, but I really think you ought to consider some kind of "has a real proper numeric value" function. It feels like it fits in to the library (certainly much more than even and odd IMO!) and I can see that kind of thing being useful in the `ow` library too.

**Comment by sindresorhus** [comment]
I wish we could just make `is.number(NaN) => false`... I can't think of any scenario where I would want that to be true. I'm happy to add a utility method for this though. We just need to find a good name for it.

**Comment by alexrussell** [comment]
> I can't think of any scenario where I would want that to be true.

Haha, yeah, summarised it nicely.

My best ideas are:

- `is.numeric` - short and snappy, but does possibly suggest the allowing of numeric strings like `"8"`, `"+4.78e+8"`, etc., which I wouldn't really expect this thing we're trying to make actually do
- `is.numericValue` - kinda same issue, but at least numeric *value* suggests something more numbery than stringy
- `is.aNumber` - kind of a lighthearted riff on `NaN`, but then clashes with `is.number` a bit too easily and may confuse
- `is.actuallyANumber` - same deal but certainly less clashy, also slightly more lighthearted
- `is.real`/`is.realNumber` - this has legs: is mathematically true (as far as I know - I am not a mathematician, so please do correct me if I'm wrong) for the zeroes, all negative and positive numbers, integers, floats and even the Infinities. Excludes imaginary and complex numbers, but JS numbers don't handle complex numbers so we're safe there. `is.real` is nicer as it's shorter, but only makes sense at-a-glance if you're already in a mathematical context. From the context of a library that is general type checking, "real" may have wider connotations on its own (e.g. "not null or undefined").

**Comment by sindresorhus** [comment]
I'm been thinking about this a lot, and I'm now leaning towards just changing `is.number()` to not accept `NaN`. It can work if we clearly document that it does not accept `NaN`. Just because `typeof` is broken, doesn't mean that we can't do better. This package is all about creating the most user-friendly type checks.
