### ISSUE TITLE
`is.urlString()`

### ISSUE THREAD

**Issue by itaisteinherz** [sindresorhus/is#71]
Since checking if a given value is a valid URL is quite common, I think having a method such a method in `is` would be very useful (this could be done using [`is-url-superb`](https://github.com/sindresorhus/is-url-superb)).

I'm not sure if this directly aligns with the goals of the module, as a URL isn't really a data structure / type / object, but this method will still be useful in many cases. Also, one could argue that you could just use `is-url-superb` directly, but having this method in `is` would still be a good addition.

**Comment by sindresorhus** [comment]
I don't think it's worth adding a dependency for this, but maybe we could just do a simple check like this:

```js
const isUrl = url => {
	try {
		new URL(url);
		return true;
    } catch (_) {
		return false;
    }
};
```

**Comment by itaisteinherz** [comment]
I could open a PR to add this, but we should probably wait for more feedback.

**Comment by gioragutt** [comment]
Will this support hosts that don’t have like a ‘.com’ in the domain? F.e in my work we have our PCs mapped in the DNS to just the names

**Comment by sindresorhus** [comment]
This is "PR welcome" now.

**Comment by itaisteinherz** [comment]
I’ll open a PR later today.
