### ISSUE TITLE
Importing this module mutates global Symbol.observable

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/is#72]
This module imports `symbol-observable`, which patches global `Symbol.observable`.
I just spent half an hour tracking down a bug which was caused by this - rxjs uses and checks for the presence of either `Symbol.observable` (if available) or of `"@@observable"`. If RxJS was imported first and some Observable created, it would receive the `"@@observable"` shim. If then this module is imported, it mutates `Symbol.observable`. If then some dependency imports a different version of RxJS, it receives the `Symbol.observable`, and Rx `from()` is unable to recognize the Observable as an Observable.

**Comment by sindresorhus** [comment]
Ack, yeah, I've seen problems with that package previously in other places.

Any suggestions on how we should change the check?

I guess we could do something like this:

```diff
- export const observable = (value: unknown) => Boolean(value && (value as any)[symbolObservable] && value === (value as any)[symbolObservable]());
+ export const observable = (value: unknown) => {
+ 	if (!value) {
+ 		return;
+ 	}
+
+ 	const symbol = Symbol.observable || '@@observable';
+ 	const symbolValue = (value as any)[symbol];
+
+ 	return Boolean(symbolValue && value === symbolValue());
+ };
```

**Comment by sindresorhus** [comment]
Actually, this check would be better:

```js
export const observable = (value: unknown) => {
	if (!value) {
		return false;
	}

	if ((value as any)[Symbol.observable] && value === (value as any)[Symbol.observable]()) {
		return true;
	}

	if ((value as any)['@@observable'] && value === (value as any)['@@observable']()) {
		return true;
	}

	return false
};
```

Thoughts?

**Comment by gioragutt** [comment]
@felixfbecker but when you think `observable`, you at least know that when you `.subscribe()` you get back a `Subscription`, something that you can't enforce if you just have `.subscribe`. checking for the symbols at least makes sure that it'd have that API (because it was implemented in a certain way and the symbols exist).

**Comment by sindresorhus** [comment]
> It would probably be best to copy what Rx does, i.e. use Symbol.observable if it exists, otherwise use '@@observable'.

So https://github.com/sindresorhus/is/issues/72#issuecomment-444738749 then?

**Comment by felixfbecker** [comment]
Yup
