### ISSUE TITLE
Add `is.url()`

### ISSUE THREAD

**Issue by itaisteinherz** [sindresorhus/is#75]
Continuing the discussion over at #73, we could add another method named `is.url` that detects if a given `value` is either a `string` URL or a `URL` instance:

```typescript
const url = (value: unknown) => urlString(value) || urlInstance(value);
```

**Comment by sindresorhus** [comment]
I'm gonna pass on this as it's too ambiguous. I think most users when just reading the code `is.url(value)` would assume it worked like `is.urlString()`, not `urlString(value) || urlInstance(value)`.
