### ISSUE TITLE
Feature request: duck typing

### ISSUE THREAD

**Issue by lonix1** [sindresorhus/is#79]
In some cases `is.instanceof` doesn't work and we need to use duck typing.

Something like

```js
is.equivalent(objectBeingTested, [members, to, look, for]): boolean;
```

Used like this:

```js
if (!is.equivalent(myAnimal, [Animal.name, Animal.species, Animal.size]))
  throw Error("Not an animal!");
```

I'm not sure what is the best method signature, but you get the idea.

I'm also not sure what is the best name, `is.equivalent()` is maybe incorrect as that implies testing two objects that are fully equivalent. Maybe something like `is.duckTypeof()`, `is.duckType()`, `is.ducktype()`.

**Comment by lonix1** [comment]
I'm doing something like this

````
function isDucktype(value: unknown, properties: any[]): boolean {

  if (!is.object(value))
    return false;

  if (properties.some((prop) => Object.keys(value).indexOf(prop.toString()) === -1))
    return false;
}
````

**Comment by brandon93s** [comment]
If you're using TypeScript, Duck-Typing should be occurring natively provided Type Guards are leveraged to narrow down object types.  Alternative to the implementation above, a custom predicate could be used with `is.all`:

```ts
function compatible(input: object, keys: string[]): boolean {
  const predicate = (value:unknown) => Object.keys(input).includes(value as string)
  return is.all(predicate, ...keys);
}
```
