### ISSUE TITLE
Create-react-app/react-scripts fails to build with this module

### ISSUE THREAD

**Issue by fael** [sindresorhus/is#8]
The "problematic" line is: `const getObjectType = x => toString.call(x).slice(8, -1)`

I am not sure if it's a webpack problem or react-script or this library.

Could you help?

<img width="579" alt="screen shot 2017-09-26 at 23 38 01" src="https://user-images.githubusercontent.com/72215/30887597-f6d36486-a313-11e7-8348-64e511632fc6.png">

React-scripts: 1.0.13

And thank you for your great work

**Comment by gioragutt** [comment]
@fael could you provide a short way to reproduce?

aka something of that sort:

```bash
npm i -g create-react-app
create-react-app my-app
cd my-app
npm i -g @sindreorhus/is
npm run build
```

**Comment by fael** [comment]
Sure, https://asciinema.org/a/EkIAiIux8wajGbmSIGStos116

**Comment by gioragutt** [comment]
try `import * as is from '...'` instead of `import is from '...'`

**Comment by gioragutt** [comment]
@fael `asciinema` is fucking amazing dude. Wtf.

**Comment by fael** [comment]
It did not work, neither `import { default as is }`

I ejected CRA, did some debugging and found that one Webpack plugin is failing to progress the module and it seems that this issue has been happening quite often as the print screen shows.

![screen shot 2017-09-27 at 14 08 31](https://user-images.githubusercontent.com/72215/30915333-6197f26c-a38e-11e7-8508-8700452d4795.png)

Anyways, when I have time I'll look into it again, for now, I'm gonna use an alternative solution, as there are many ones just for primitive type checking for lazy people like me.

And yeah, I also really like asciinema and it was my first time using it, but it's like recording a video, sometimes it takes more than one shot, mine was four. :laughing:

**Comment by gioragutt** [comment]
Can you maybe try to change:
```typescript
const toString = Object.prototype.toString;
const getObjectType = x => toString.call(x).slice(8, -1);
```
to
```typescript
const getObjectType = x => Object.prototype.toString.call(x).slice(8, -1);
```
and see if it happens?

I just want to offer all the small possible things that might make this happen.

**Comment by sindresorhus** [comment]
`create-react-app` is unable to transpile dependencies. This will be fixed by https://github.com/sindresorhus/is/issues/9, as we will transpile it on publish time.

**Comment by gioragutt** [comment]
@fael have you tried this again? I'm using it in my CRA project and it works
