### ISSUE TITLE
`is.version()`

### ISSUE THREAD

**Issue by itaisteinherz** [sindresorhus/is#82]
This might be a bit of an edge-case, but having a method which checks if a given string is a valid version number is useful in some cases. This could be implemented similarly to the way [`isValidVersion`](https://github.com/sindresorhus/np/blob/6df47b909be697687538b52f00f8b5875738933e/source/version.js#L7) is in [`np`](https://github.com/sindresorhus/np):

```js
const semver = require('semver');
const isValidVersion = input => Boolean(semver.valid(input));
```

This would require us to add the [`semver`](https://github.com/npm/node-semver) dependency, though.

**Comment by gioragutt** [comment]
You can keep `semver` as a `peerDependency` and only try to load it, and throw an error if it does not exist....

And I would do `!!semver.valid(input)` over `Boolean`.

**Comment by itaisteinherz** [comment]
> You can keep `semver` as a `peerDependency` and only try to load it, and throw an error if it does not exist....

That's one option, however it seems to me like it would result in ambiguous and unpredictable behavior when using the method.

> And I would do `!!semver.valid(input)` over `Boolean`.

Why? That just makes the code less readable (it took me an hour to understand what `!!` does and why it's being used).

**Comment by gioragutt** [comment]
`!!` is pretty standard in JS. Look at `is.truthy`.
Second, look at `is(...)`, there's explicit warning about using Boxed types.
No reason to use `Boolean` when you can use `boolean`.

**Comment by itaisteinherz** [comment]
> `!!` is pretty standard in JS. Look at `is.truthy`.

https://github.com/sindresorhus/is/blob/79144f95425e75a601e208d83cc0eb6c8ad7565d/source/index.ts#L194

> No reason to use `Boolean` when you can use `boolean`.

Also true.

But in this case we can just use `is.truthy` and avoid the debate 😉

**Comment by gioragutt** [comment]
Haha yeah, I agree 👍

**Comment by gioragutt** [comment]
Possible implementation of `is.semver`:

```typescript
let semverLib = null;
const semver = (input: unknown): input is string => {
  if (!semverLib) {
    try {
      semverLib = require('semver');
    } catch (e) {
      throw new Error('semver dependency is not fullfilled')
    }
  }
  return is.truthy(semverLib(input));
}
```

**Comment by itaisteinherz** [comment]
> `return is.truthy(semverLib(input));`

`semverLib(input)` => `semverLib.valid(input)` (see [the docs](https://github.com/npm/node-semver#functions))

**Comment by gioragutt** [comment]
Yeah, my bad.

**Comment by gioragutt** [comment]
@sindresorhus, @brandon93s your opinion on this?
I think the tricky part here is wether we make `semver` a peerDependency or a normal dependency, and if we make it peer, what's the best practice in this situation?

**Comment by brandon93s** [comment]
Making it a `peerDependency` seems to provide little to no value. If the user has to install it on their own, they could just as easily consume it directly.

Since a stable and maintained solution exists, I'm not sure it belongs in `is` since the proposed solution is simply a passthrough.

**Comment by sindresorhus** [comment]
I don't think it belongs in `is`. We could maybe link to it from the readme.
