### ISSUE TITLE
[Question] Works on frontend?

### ISSUE THREAD

**Issue by lonix1** [sindresorhus/is#83]
I'm using this on the server side and it's great (and thank you very much! :+1:).

I tried to use it in on the client side (angular) but my app won't compile because 

> Module not found: Error: Can't resolve 'url' in '......./node_modules/@sindresorhus/is/dist'

And I found this in the module:

````
// TODO: Use the `URL` global when targeting Node.js 10
// tslint:disable-next-line
const URLGlobal = typeof URL === 'undefined' ? require('url').URL : URL;
````

Is there a way to use this on the frontend, or is that impossible? The docs didn't say that *I can't* use it on the frontend, so I wasn't sure. If the only thing stopping its use on the frontend is the `url` module, maybe there is a way to workaround that?

**Comment by brandon93s** [comment]
It works fine in a new angular-cli app: https://codesandbox.io/s/xvlxlw0yzz.

Assuming you're using webpack, you'll want to make sure `NodeStuffPlugin` and `NodeSourcePlugin` are enabled in your build process:

- https://webpack.js.org/configuration/node/
- https://github.com/webpack/node-libs-browser#readme
- https://github.com/defunctzombie/node-url

**Comment by lonix1** [comment]
The latest angular abstracts webpack so you can't configure it. What then?

**Comment by brandon93s** [comment]
Do you have an example repository I can take a look at? The codesandbox link is also latest and is working out of the box.

**Comment by lonix1** [comment]
The latest angular is 7 and that sample is 5. I think they made that change (abstracting webpack) in 6.

I don't have a sample app, so I'll dig into your one and try find the problem. Thanks.
