### ISSUE TITLE
Refactor to use type-fest

### ISSUE THREAD

**Issue by thiagodp** [sindresorhus/is#85]
Please see https://github.com/sindresorhus/type-fest/issues/10

**Comment by sindresorhus** [comment]
Yup, that's the plan. Just wanted `type-fest` to mature a little bit first.

**Comment by abalmos** [comment]
@sindresorhus Can this happen now? I am currently blocked on: https://github.com/sindresorhus/is/issues/108

**Comment by sindresorhus** [comment]
Sure

**Comment by willrnch** [comment]
Any update on this @sindresorhus?
