### ISSUE TITLE
Add "asserts" variants of type guards

### ISSUE THREAD

**Issue by joelpurra** [sindresorhus/is#91]
A new typescript language feature is slated for the [v3.7.0 milestone](https://github.com/microsoft/TypeScript/milestone/98): `asserts`. I think adding new [`asserts value is T`](https://github.com/microsoft/TypeScript/pull/32695) variants of the type guard-enabled functions in `is` would be very useful. It would reduce the often repetitive "if-not-typeof-throw" pattern to a single line, while narrowing types.

Example implementation:

```typescript
is.assertedString = (value: unknown): asserts value is string {
  if (!is.string(value)) {
    throw new TypeError("Not a string.");
  }
}
```

<details>Without asserts:

```typescript
function f(input: unknown) {
  if (!is.string(input)) {
    throw new TypeError("Not a string.");
  }
  // input has type string here.
}
```
</details>

With asserts:

```typescript
function f(input: unknown) {
  is.assertedString(input);
  // input has type string here.
}
```

Function naming to be discussed.

**Comment by sindresorhus** [comment]
I think it should be under a separate namespace with exactly the same methods as `is`:

```ts
import {assert} from '@sindresorhus/is';

assert.string(foo);
```

**Comment by sindresorhus** [comment]
TypeScript 3.7 is now out: https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/

PR welcome :)

**Comment by aleclarson** [comment]
Any reason why type assertions shouldn't have their own package?
```ts
import assert from '@sindresorhus/assert'
```
I think most TypeScript programs don't need them.

**Comment by sindresorhus** [comment]
@aleclarson The assertions are exactly the same is the `is` checks other than asserting instead of type checking. I think it makes more sense to have everything in one package, from a maintenance perspective.

---

> I think most TypeScript programs don't need them.

I would use them a lot in my TypeScript projects.
