### ISSUE TITLE
Cannot find name 'Element'

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/is#94]
🤗🍰🍴

I think we got hit by something here in the last `is` release: https://github.com/googleapis/nodejs-pubsub/issues/769

**Comment by gioragutt** [comment]
I think it's related to #93.
`Element` is probably from the dom ts lib.

**Comment by sindresorhus** [comment]
Ah, I missed that one. The `Element` type is really complex. Doesn't look like bundling the needed DOM types will be feasible... I have reverted it and done a new release: https://github.com/sindresorhus/is/releases/tag/v1.2.0

We'll have to wait for https://github.com/microsoft/TypeScript/issues/33111.
