### ISSUE TITLE
How do you check if a value is of any generic type?

### ISSUE THREAD

**Issue by matthew-dean** [sindresorhus/is#95]
I'd like to do something like this:

```ts
class Foo {}
class Bar {}

is(value, [Foo, Bar])
```
How do I use this library to check that the value is one of a given type, or the simpler (if I need to abstract it:
```ts
is(value, Foo)
```
Does this library only support built-in JavaScript primitives / objects?

**Comment by gioragutt** [comment]
Honestly? ```value instanceof Foo``` 🤷🏻‍♂️
