### ISSUE TITLE
feature request: `oneOf` that allows you to check a value against multiple predicates

### ISSUE THREAD

**Issue by scraggo** [sindresorhus/is#98]
Similar to https://github.com/sindresorhus/is/issues/95, but this is more of a feature request: `.oneOf` method that allows you to check a value against multiple predicates.

I've implemented it by doing the following:
```js
is.oneOf = (item, predicatesArray) => {
  return predicatesArray.some(predicate => predicate(item));
}
```

To use it:
```js
it("uses is predicates for a true match", () => {
      expect(is.oneOf("hi", [is.function, is.string, is.object])).toEqual(true);
    });
```

**Comment by sindresorhus** [comment]
Sounds useful.

I do wonder if we could change the existing `any`/`all` methods to support this use-case too.

Maybe if we change `is.any(is.string, {}, true, '🦄');` to `is.any([{}, true, '🦄'], is.string);`, we could allow multiple inputs on each side:

```js
is.any([{}, true, '🦄'], is.string);
is.any('🦄', [is.string, is.boolean]);
```

Thoughts? Other ideas?

**Comment by scraggo** [comment]
Adding it to `.any` like you’re suggesting works for me. Personally, I hesitated to overload it because I didn’t want there to be potential for confusion with how it already works. But the way you added it avoids a breaking change.  :)

I’m not sure what the use case for `.all` is since a given input can only be one type, unless I’m mistaken!

If you decide it’s worthwhile, I’m happy to make a PR.

**Comment by sindresorhus** [comment]
Hmm, I don't think we actually need to change the order. We can just add an overload to `is.any` like this:

`.any(predicates[], ...values)`

```js
is.any([is.string, is.number], {}, true, '🦄');
//=> true

is.any([is.boolean, is.number], 'unicorns', [], new Map());
//=> false
```

PR welcome for that.

**Comment by scraggo** [comment]
Sounds great to me 👍 - I'll have a PR hopefully shortly
